# Generated by Django 3.1.7 on 2021-04-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('framac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectioncategory',
            name='category',
            field=models.CharField(choices=[('PC', 'procedure'), ('PP', 'property'), ('LM', 'lemma'), ('AS', 'assertion'), ('IN', 'invariant'), ('PR', 'precondition'), ('PO', 'postcondition')], max_length=2),
        ),
    ]
