# Generated by Django 3.1.7 on 2021-04-30 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('framac', '0002_auto_20210412_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesection',
            name='code_or_comment',
        ),
        migrations.AddField(
            model_name='filesection',
            name='line_from',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='filesection',
            name='line_to',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='directory',
            name='is_placed_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='framac.directory'),
        ),
    ]
